FROM tiangolo/nginx-rtmp:latest

# Copy the frontend build files and the NGINX config file
COPY build /usr/share/nginx/html
COPY nginx.conf /etc/nginx/nginx.conf

# Expose ports for HTTP and RTMP
EXPOSE 80
EXPOSE 1935

CMD ["nginx", "-g", "daemon off;"]
