services:
  backend:
    build:
      context: . # Root directory for backend
      dockerfile: Dockerfile # Backend Dockerfile in root directory
    ports:
      - "8080:8080"
    volumes:
      - .:/usr/src/app
    command: node backend/index.js

  nginx:
    build:
      context: .
      dockerfile: Dockerfile.nginx # Specifies the custom NGINX Dockerfile
    ports:
      - "80:80" # HTTP port
      - "1935:1935" # RTMP port

  kurento:
    build:
      context: .
      dockerfile: Dockerfile.kurento
    ports:
      - "8888:8888"
      - "8889:8889"
