services:
  backend:
    build:
      context: . # Root directory for backend
      dockerfile: Dockerfile # Backend Dockerfile in root directory
    ports:
      - "8080:8080"
    volumes:
      - .:/usr/src/app
    command: node backend/index.js

  nginx:
    image: alfg/nginx-rtmp
    ports:
      - "80:80" # HTTP port
      - "1935:1935" # RTMP port
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf
    environment:
      - NGINX_VERSION=1.20.0

  kurento:
    build:
      context: .
      dockerfile: Dockerfile.kurento
    ports:
      - "8888:8888"
      - "8889:8889"
