services:
  backend:
    build:
      context: . # Context set to the root directory
      dockerfile: Dockerfile # Use the Dockerfile from the root directory
    ports:
      - "8080:8080" # Mapping port 8080 on host to port 8080 in the container
    volumes:
      - ./uploads:/usr/src/app/uploads # Mount uploads directory from host to container
